# Generated by Django 4.0 on 2023-06-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, upload_to='static/images')),
                ('cv', models.FileField(blank=True, upload_to='static/cv')),
            ],
        ),
    ]
